### ISSUE TITLE
ERROR: No matching distribution found for pywin32==306

### ISSUE THREAD

**Issue by 2h311** [KaranParwani/monitor_transactions#1]
What python version are you using? I'm on 3.10 and I have issues install pywin32, had to go with pypiwin32.

**Comment by KaranParwani** [comment]
Python 3.11.2

**Comment by 2h311** [comment]
I see

**Comment by 2h311** [comment]
Did you adapt the code to work in a Linux environment? Also, I see you didn't use the template you created, why is that?

**Comment by KaranParwani** [comment]
No I am using Windows 8 as of now for the development, Soon I will be using Ubuntu for this

**Comment by 2h311** [comment]
i see. nice work
